---

name: 'Validate pull request'

on: [workflow_dispatch, pull_request]

defaults:
  run:
    shell: bash

permissions:
  id-token: write # needs to log into aws
  contents: read

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'go-template'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
